---
title: "example"
author: "Xingqi"
date: "November 17, 2014"
output: html_document
---


```{r echo=FALSE, results='hide',message=FALSE}
library(fastR)
library(Hmisc)
```


```{r}
data(coagulation,package="faraway")
summary(coag~diet, data=coagulation,fun=favstats) 
coag.xyplot <- xyplot(coag~diet,coagulation)
coag.bwplot <- bwplot(coag~diet,coagulation)
coag.xyplot
coag.bwplot
```


```{r}
coag.model <- lm(coag~diet,coagulation)
summary(coag.model)
```

7.3.3

```{r}
coag <- coagulation
coag$x1 <- coag$diet=='B'
coag$x2 <- coag$diet=='C'
coag$x3 <- coag$diet=='D'
coag.model <- lm(coag~x1+x2+x3,coag)
coag.model1 <- lm(coag~1,coag)
anova(coag.model1,coag.model)

```


```{r}
coag.model <- lm(coag~diet,coagulation)
anova(coag.model)
```

Example 7.3.4

```{r}
stats <- function(x) {
+         c( mean = mean(x),
+ 	   SS = sum( (x - mean(x))^2 )
+ 	 )}
summary(coag~diet, data=coagulation, fun=stats) -> s; s
s <- unclass(s)
grandMean <- mean(coagulation$coag); grandMean
SST <- sum((coagulation$coag - grandMean)^2); SST
SSE <- sum((coagulation$coag - groupMean)^2); SSE
SSM <- sum((groupMean - grandMean)^2 ); SSM
```


```{r}
coag.model <- lm(coag~diet,coagulation)
anova(coag.model)
```

```{r}
coag.model <- lm(coag~diet,coagulation)
summary(coag.model)
```


```{r}
coag.altmodel <- lm(coag~diet-1,coagulation)
summary(coag.altmodel)
```

Example 7.3.5

```{r}
summary(pollution~location,data=airpollution,fun=mean)
```

```{r}
airp.model<-lm(pollution~location,airpollution)
anova(airp.model)
```

Example 7.3.6

```{r}
airp <- airpollution; airp$loc <- as.numeric(airp$location); airp
model <- lm(pollution~location, airp)
model2 <- lm(pollution~  1 + (loc==3), airp)
anova(model2,model)
```

```{r}
airp$x<-with(airp,((loc==2)+ 0.5*(loc==3)))
model3<-lm(pollution~1 + x,airp)
anova(model3,model)
```

```{r}
airp$x1<- with(airp,((loc==1)+ 0.5*(loc==3)))
airp$x2<- with(airp,((loc==2)+ 0.5*(loc==3)))
model3<-lm(pollution~1+ x1 +x2,airp)
anova(model3,model)
```

Example 7.3.13

```{r}
airp.aov<-aov(pollution~location,airpollution)
TukeyHSD(airp.aov)
```

```{r}

```

